timeInSecs: 0
Quests:
  - "Találj barna birkát (3%)"
  - "Találj pókon ülo csontvázat (1%)"
  - "Találj Egy fegyveres zombit (0,33%)"
  - "Találj egy Rózsaszín birkát (0,164%)"
  - "Találj bébi barna birkát (0,15%)"
  - "Találj egy Mycelium Biomeot (0,05%)"
  - "Találj egy rózsaszín bébi birkát (0,0082%)"
  - "Találj egy mérgezö krumplit (2%)"
  - "#Keljen ki egy kiscsirke egy tojásból (12,5%)"
  - "Kapj nyúllábat (10%)"
  - "Idézz le egy Endermiteot (5%)"
  - "Kapj egy almát (0,5%)"
  - "OP Aranyalma egy sivatagi templomból (2,6%)"
  - "Más szinü ló születik kettő eltérö szülötöl (2,22%)"
  - "Kapj vasat egy Zombietól (0,83%)"
  - "Kapj egyszerre egy almát és egy csemetét egy levélbol (0,025%)"
  - "Horgássz egy tintazsákot (0,12%)"
  - "Egy barna gyerek Múúmba (0,00098%)"
  